repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json,*.ambr"
        exclude_types: [csv, json, html]
        exclude: ^tests/fixtures/|^tests/snapshots/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args:
          - --extend-select=I
          - --fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --strict
        language: system
        types: [python]
