language: python
matrix:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV=lint
    - python: "3.8"
      env: TOXENV=cov
      after_success: coveralls
    - python: "3.7"
      env: TOXENV=py37
install: pip install -U tox coveralls
script: tox
deploy:
  provider: pypi
  user: andrewsayre
  password:
    secure: McrvG3G6FsVfkdqXHi15O7x47fzmnD3lnsKpLEsU0ueMZYA+tnq3RFS9OAIgBP6OF5Zppo2HgcqZY+56xbMpioVVcq5oIY3+J6Is/KpicoUZLEg6hw0Nr+34QfplqeSLH02Vdze1tKhRnvepjiFhoM2TTicOQS7utNaaCS+5CpDvuLO5Kxg6urQ+c0A/ALqRzNaAoz83XJTGpVzSi4mkWeZbDjiN6tsxPMc/5lSiZZGFx05dBLhIhChM3tLijuRJcGtZkla0eZXtwkaHEBbzkqW0b7coqR0QL+QdtPebZlGZyKQd/tj8Xjle5ju5dLoMZ96dC+meCyRu7JNpWx048gZ24bU85cZVvAp4TbOokR6BaODqSjPyXB7klUnpuRs5C5iVf6a37Gn9bDq8qXrOR/LdRUdtGPkoGJV6XCLfPxc2FCPqdZe7wv76vdZQK/ssHGcb/oYCvBL9cBjV/w0HujWC90H+VCwWFnzBoTxD8/YvsWk0g6sIZ22W9XTxJ3snfbvosq+JU2w/WoDGHqfTmwm+BHL1S4QhecO0HEW/KVbYcIFb70X0IlK2L2FODJnuzioTZMeao7vkbFPxPscE5PbMj3/lboNo1haJ3TcmR7WlymwPNTC4ITd21yODct5xF1fpqN3yuaMaVACE4M4bU/NQayB28uSagxQfc5oKUPY=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
    condition: "$TOXENV = lint"
