#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

# Upgrade pip and install UV
pip install --upgrade pip
pip install uv

# Setup virtual environment
if [[ -n "${VIRTUAL_ENV:-}" && -d "$VIRTUAL_ENV" ]]; then
  rm -rf "$VIRTUAL_ENV"
fi
uv venv $VIRTUAL_ENV

# install dependencies
uv pip install -r requirements.txt -r test-requirements.txt