name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request: ~

jobs:
  lint:
    name: "Check style, lint, and typing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test-requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -r requirements.txt -r test-requirements.txt --upgrade --system
      - run: pre-commit install-hooks
      - name: Spelling (codespell)
        run: pre-commit run --all-files --hook-stage manual codespell --show-diff-on-failure
      - name: Lint (Ruff)
        run: pre-commit run --all-files --hook-stage manual ruff --show-diff-on-failure
      - name: Format (Ruff)
        run: pre-commit run --all-files --hook-stage manual ruff-format --show-diff-on-failure
      - name: Format (Pylint)
        run: pre-commit run --all-files --hook-stage manual pylint --show-diff-on-failure
      - name: Typing my[py]
        run: pre-commit run --all-files --hook-stage manual mypy --show-diff-on-failure

  tests:
    name: "Run tests on ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test-requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -r requirements.txt -r test-requirements.txt --upgrade --system
      - name: Run pytest on ${{ matrix.python-version }}
        run: pytest

  coverage:
    name: "Check code coverage"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('test-requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install -r requirements.txt -r test-requirements.txt --upgrade --system
      - name: Run pytest on ${{ matrix.python-version }}
        run: pytest --cov --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
